### ISSUE TITLE
Expand the example of configuring TCP-AO

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#176]
The current example of configuring TCP-AO as part of a BGP session does not show configuration of send/receive ids typically configured by the client.

Even the keychain part of the configuration could be expanded based on the example in the TCP YANG module.

**Comment by jhaas-pfrc** [comment]
After discussion at today's BGP YANG meeting, I think we've come to the conclusion that the proper use pattern for TCP-AO is simply to refer to the keychain name.  The tcpm YANG model has a number of issues that will need resolution outside of IDR.  If it turns out that we need actions in our module as that set of issues resolve, we can deal with it then.

Meanwhile, I suggest we close this issue.

**Comment by mjethanandani** [comment]
I checked our model and as currently defined it already refers to a keychain, and allows for configuration of the following items:

```
       |  |  +--rw secure-session
       |  |  |  +--rw (option)?
       |  |  |     +--:(ao)
       |  |  |     |  +--rw enable-ao?             boolean
       |  |  |     |  +--rw send-id?               uint8
       |  |  |     |  +--rw recv-id?               uint8
       |  |  |     |  +--rw include-tcp-options?   boolean
       |  |  |     |  +--rw accept-ao-mismatch?    boolean
       |  |  |     |  +--rw ao-keychain?
       |  |  |     |          key-chain:key-chain-ref
```

The only thing missing in this display is the RNextKeyId, which is anyway a ro node, and the TCP session can fetch that from within its own model, once the AO session has been established.

Thus both the BGP model, and the example in A.3 is sufficient for now. Thus closing the issue.
