### ISSUE TITLE
Features and attributes that lack references

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#32]
These features/attributes lack references. IETF WG (mostly IDR) needs to spin-up documents for these features.

- no-client-reflect for Route Reflector.
- always-compare-med
- ignore-as-path-length
- external-compare-router-id
- advertise-inactive-routes
- ignore-next-hop-igp-metric

**Comment by mjethanandani** [comment]
Assigned to Susan Hares as co-author and chair.

**Comment by suehares** [comment]
My original suggestion for these features was to have these 5 policy features written up as a short extension draft for IDR that goes along with the BGP model.   My reasoning was that I wanted to make sure that the IDR WG agreed with the features descriptions rather than delay the model. 

On 6/22/2021 - I'm not sure that we should not just put in our best guess. 

Example of why I suggested that we should have IDR discuss these point. 

1) always-compare-med - is there in open-config, 2 variants in cisco, 2 variants in juniper, 2 variants in huawei. 

 

http://ops.openconfig.net/branches/models/master/docs/openconfig-bgp.html#openconfig-bgp-data
https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/16046-bgp-med.html 
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/path-selection-edit-protocols-bgp.html
https://support.huawei.com/enterprise/en/doc/EDOC1100064351/c0dda3f3/compare-different-as-med

**Comment by jhaas-pfrc** [comment]
These have all been implemented.
